[package]
name = "wiiload-proto"
version = "0.1.0"
authors = ["Marime Gui <lepro.guillaume@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniz_oxide = "0.4.1"
